# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hercules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_num', models.CharField(max_length=250, verbose_name='asset number')),
                ('desciption', models.CharField(max_length=250, verbose_name='description')),
                ('serial_num', models.CharField(max_length=250, verbose_name='serial number')),
                ('asset_type', models.CharField(max_length=250, verbose_name='type')),
                ('location', models.CharField(max_length=250, verbose_name='location')),
                ('status', models.CharField(choices=[('in stock', 'InStock'), ('in use', 'InUse'), ('in repair', 'InRepair'), ('broken', 'Broken')], default='in stock', max_length=10, verbose_name='status')),
                ('owner', models.CharField(max_length=250, verbose_name='owner')),
                ('assignee', models.CharField(max_length=250, verbose_name='assignee')),
                ('order_num', models.CharField(max_length=250, verbose_name='order num')),
                ('note', models.TextField()),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
