# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-20 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Hercules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHercules',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('asset_num', models.CharField(max_length=250, verbose_name='asset number')),
                ('desciption', models.CharField(max_length=250, verbose_name='description')),
                ('serial_num', models.CharField(max_length=250, verbose_name='serial number')),
                ('asset_type', models.CharField(max_length=250, verbose_name='type')),
                ('location', models.CharField(max_length=250, verbose_name='location')),
                ('status', models.CharField(choices=[('in stock', 'InStock'), ('in use', 'InUse'), ('in repair', 'InRepair'), ('broken', 'Broken')], default='in stock', max_length=10, verbose_name='status')),
                ('owner', models.CharField(max_length=250, verbose_name='owner')),
                ('assignee', models.CharField(max_length=250, verbose_name='assignee')),
                ('order_num', models.CharField(max_length=250, verbose_name='order num')),
                ('note', models.TextField()),
                ('recorded', models.DateTimeField(blank=True, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical hercules',
            },
        ),
    ]
